services:
  powerstore_exporter:
    image: schluo/powerstore_exporter:latest
    container_name: powerstore_exporter
    restart: unless-stopped
    user: '1000'
    ports:
      - 9002:9006
    environment:
      - ARRAY=10.10.10.10
      - USER=admin
      - PASSWORD=password
      - PORT=9006
      - INTERVAL=20
      - METRIC=performance_metrics_by_appliance
